services:
  redis:
    container_name: api-go-dev_redis
    user: ${CONTAINER_UID}:${CONTAINER_GID}
    build:
      dockerfile: ./Dockerfile.redis
      args:
        CONTAINER_UID: ${CONTAINER_UID}
        CONTAINER_GID: ${CONTAINER_GID}
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data

  postgres:
    container_name: api-go-dev_postgres
    shm_size: 128mb
    user: ${CONTAINER_UID}:${CONTAINER_GID}
    build:
      dockerfile: ./Dockerfile.postgres
      args:
        CONTAINER_UID: ${CONTAINER_UID}
        CONTAINER_GID: ${CONTAINER_GID}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}

  backend:
    image: api-go-dev_backend
    container_name: api-go-dev_backend
    user: ${CONTAINER_UID}:${CONTAINER_GID}
    runtime: runsc
    build:
      dockerfile: ./Dockerfile
      args:
        CONTAINER_UID: ${CONTAINER_UID}
        CONTAINER_GID: ${CONTAINER_GID}
    volumes:
      - vscode-server-data:/home/developer/.vscode-server
      - go-data:/go
      - ../api-go:/workspace:cached
    ports:
      - 127.0.0.1:${BACKEND_PORT}:80
    depends_on:
      - postgres
      - redis

volumes:
  vscode-server-data:
    name: "api-go-dev_vscode-server-data"
  go-data:
    name: "api-go-dev_go-data"